import mongoose from "mongoose";
import dotenv from "dotenv";
import Appliance from "../models/Appliance.js";

// Load config
dotenv.config();

const appliances = [
  {
    serialNo: "JTD-512312",
    theatreName: "Kriplle Square",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "812 Kbps",
    planStartDate: new Date("2023-10-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "offline",
    downloadStatus: "failed",
    osVersion: "5.2.1.3",
    storage: "828 GB",
  },
  {
    serialNo: "JTD-512313",
    theatreName: "Cinema Hall",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "300 Kbps",
    planStartDate: new Date("2023-09-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "online",
    downloadStatus: "succeeded",
    osVersion: "6.0.1",
    storage: "512 GB",
  },
  {
    serialNo: "JTD-512314",
    theatreName: "PVR Cinemas",
    location: {
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "2 Gbps",
    avgBandwidth: "1 Gbps",
    planStartDate: new Date("2023-08-15T10:00:00Z"),
    billingCycle: "annual",
    deviceStatus: "online",
    downloadStatus: "downloading",
    osVersion: "5.0.0",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512315",
    theatreName: "INOX",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1.5 Gbps",
    avgBandwidth: "700 Mbps",
    planStartDate: new Date("2023-07-01T10:00:00Z"),
    billingCycle: "quarterly",
    deviceStatus: "offline",
    downloadStatus: "cancelled",
    osVersion: "5.3.1",
    storage: "600 GB",
  },
  {
    serialNo: "JTD-512316",
    theatreName: "Carnival Cinemas",
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
    },
    ispPaymentResponsibility: "Theatre",
    bandwidth: "1 Gbps",
    avgBandwidth: "900 Kbps",
    planStartDate: new Date("2023-06-15T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "online",
    downloadStatus: "failed",
    osVersion: "5.1.3",
    storage: "700 GB",
  },
  {
    serialNo: "JTD-512317",
    theatreName: "Cinepolis",
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "800 Mbps",
    avgBandwidth: "600 Kbps",
    planStartDate: new Date("2023-05-01T10:00:00Z"),
    billingCycle: "quarterly",
    deviceStatus: "offline",
    downloadStatus: "succeeded",
    osVersion: "6.2.1",
    storage: "500 GB",
  },
  {
    serialNo: "JTD-512318",
    theatreName: "Sathyam Cinemas",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "700 Kbps",
    planStartDate: new Date("2023-04-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "online",
    downloadStatus: "downloading",
    osVersion: "5.4.2",
    storage: "900 GB",
  },
  {
    serialNo: "JTD-512319",
    theatreName: "PVR ICON",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Theatre",
    bandwidth: "2 Gbps",
    avgBandwidth: "1.5 Gbps",
    planStartDate: new Date("2023-03-01T10:00:00Z"),
    billingCycle: "annual",
    deviceStatus: "offline",
    downloadStatus: "cancelled",
    osVersion: "6.1.0",
    storage: "1.5 TB",
  },
  {
    serialNo: "JTD-512320",
    theatreName: "PVR Gold",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "750 Kbps",
    planStartDate: new Date("2023-02-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "online",
    downloadStatus: "failed",
    osVersion: "6.3.1",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512321",
    theatreName: "Raj Mandir",
    location: {
      city: "Jaipur",
      state: "Rajasthan",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "400 Kbps",
    planStartDate: new Date("2023-01-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "offline",
    downloadStatus: "succeeded",
    osVersion: "5.5.1",
    storage: "700 GB",
  },
  {
    serialNo: "JTD-512322",
    theatreName: "PVR Anupam",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    ispPaymentResponsibility: "Theatre",
    bandwidth: "1.5 Gbps",
    avgBandwidth: "1.2 Gbps",
    planStartDate: new Date("2022-12-01T10:00:00Z"),
    billingCycle: "annual",
    deviceStatus: "online",
    downloadStatus: "failed",
    osVersion: "5.6.1",
    storage: "2 TB",
  },
  {
    serialNo: "JTD-512323",
    theatreName: "Prasad's IMAX",
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "3 Gbps",
    avgBandwidth: "2.5 Gbps",
    planStartDate: new Date("2022-11-01T10:00:00Z"),
    billingCycle: "quarterly",
    deviceStatus: "offline",
    downloadStatus: "succeeded",
    osVersion: "5.7.1",
    storage: "3 TB",
  },
  {
    serialNo: "JTD-512324",
    theatreName: "SRS Cinemas",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "700 Kbps",
    planStartDate: new Date("2022-10-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "online",
    downloadStatus: "downloading",
    osVersion: "6.0.2",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512325",
    theatreName: "Wave Cinemas",
    location: {
      city: "Noida",
      state: "Uttar Pradesh",
      country: "India",
    },
    ispPaymentResponsibility: "Theatre",
    bandwidth: "2 Gbps",
    avgBandwidth: "1 Gbps",
    planStartDate: new Date("2022-09-01T10:00:00Z"),
    billingCycle: "annual",
    deviceStatus: "offline",
    downloadStatus: "failed",
    osVersion: "6.2.0",
    storage: "2 TB",
  },
  {
    serialNo: "JTD-512326",
    theatreName: "INOX Leisure",
    location: {
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1.5 Gbps",
    avgBandwidth: "800 Mbps",
    planStartDate: new Date("2022-08-01T10:00:00Z"),
    billingCycle: "quarterly",
    deviceStatus: "online",
    downloadStatus: "cancelled",
    osVersion: "5.8.1",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512327",
    theatreName: "Carnival Cinemas",
    location: {
      city: "Ahmedabad",
      state: "Gujarat",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "750 Kbps",
    planStartDate: new Date("2022-07-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "offline",
    downloadStatus: "succeeded",
    osVersion: "6.4.1",
    storage: "1.5 TB",
  },
  {
    serialNo: "JTD-512328",
    theatreName: "E-Square",
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Theatre",
    bandwidth: "500 Mbps",
    avgBandwidth: "450 Kbps",
    planStartDate: new Date("2022-06-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "online",
    downloadStatus: "failed",
    osVersion: "5.9.1",
    storage: "500 GB",
  },
  {
    serialNo: "JTD-512329",
    theatreName: "PVR Koramangala",
    location: {
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "2 Gbps",
    avgBandwidth: "1.2 Gbps",
    planStartDate: new Date("2022-05-01T10:00:00Z"),
    billingCycle: "quarterly",
    deviceStatus: "offline",
    downloadStatus: "succeeded",
    osVersion: "6.5.1",
    storage: "2 TB",
  },
  {
    serialNo: "JTD-512330",
    theatreName: "Luxe Cinemas",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
    },
    ispPaymentResponsibility: "Theatre",
    bandwidth: "1 Gbps",
    avgBandwidth: "800 Kbps",
    planStartDate: new Date("2022-04-01T10:00:00Z"),
    billingCycle: "annual",
    deviceStatus: "online",
    downloadStatus: "downloading",
    osVersion: "6.6.1",
    storage: "1.5 TB",
  },
  {
    serialNo: "JTD-512331",
    theatreName: "Sangam Cinemas",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "750 Kbps",
    planStartDate: new Date("2022-03-01T10:00:00Z"),
    billingCycle: "monthly",
    deviceStatus: "offline",
    downloadStatus: "failed",
    osVersion: "6.7.1",
    storage: "700 GB",
  },
  {
    serialNo: "JTD-512332",
    theatreName: "INOX GVK One",
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
    },
    ispPaymentResponsibility: "Theatre",
    bandwidth: "1.5 Gbps",
    avgBandwidth: "1.2 Gbps",
    planStartDate: new Date("2022-02-01T10:00:00Z"),
    billingCycle: "annual",
    deviceStatus: "online",
    downloadStatus: "failed",
    osVersion: "6.8.1",
    storage: "2 TB",
  },
];


const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    await Appliance.deleteMany({});
    await Appliance.insertMany(appliances);
    console.log("Data seeded successfully!");
    mongoose.connection.close();
  } catch (err) {
    console.error(err.message);
    mongoose.connection.close();
  }
};

seedDB();
